name 'puppetlabs-puppetdb'
version '1.1.4'
source 'git://github.com/puppetlabs-puppet/puppetlabs-puppetdb.git'
author 'Puppet Labs'
description 'PuppetDB resource types'
summary 'PuppetDB resource types'
license 'Apache'
project_page 'https://github.com/puppetlabs-puppet/puppetlabs-puppetdb'

dependency 'cprice404/inifile', '>= 0.9.0'
dependency 'puppetlabs/postgresql', '2.x'
dependency 'puppetlabs/firewall', '>= 0.0.4'
