#!/usr/bin/env ruby
#^syntax detection

forge "https://forgeapi.puppetlabs.com"

mod 'puppetlabs/apache', '1.1.0'

mod 'puppetlabs/apt'

mod 'puppetlabs/concat'

# Official contains a bug wrt nologin shell
mod 'dashboard',
  :git => 'git://github.com/andersbs/puppetlabs-dashboard.git'

# Updated
mod 'puppetlabs/firewall'

mod 'puppetlabs/inifile'

mod 'puppetlabs/mysql'

mod 'puppetlabs/passenger'

mod 'puppetlabs/postgresql'

mod 'puppetlabs/puppetdb'

mod 'puppetlabs/ruby'

mod 'puppetlabs/stdlib'


# A module from git
# mod 'puppetlabs/ntp',
#   :git => 'git://github.com/puppetlabs/puppetlabs-ntp.git'

# A module from a git branch/tag
# mod 'puppetlabs/apt',
#   :git => 'https://github.com/puppetlabs/puppetlabs-apt.git',
#   :ref => '1.4.x'

# A module from Github pre-packaged tarball
# mod 'puppetlabs/apache', '0.6.0', :github_tarball => 'puppetlabs/puppetlabs-apache'
