forge "http://forge.puppetlabs.com"

# mod 'puppetlabs/stdlib'

# mod 'ntp',
#   :git => 'git://github.com/puppetlabs/puppetlabs-ntp.git'

# mod 'apt',
#   :git => 'https://github.com/puppetlabs/puppetlabs-apt.git',
#   :ref => 'feature/master/dans_refactor'
#mod 'puppetlabs/apt'
mod 'puppetlabs/postgresql'
mod 'dashboard', :git => 'https://github.com/grahamgilbert/puppetlabs-dashboard.git'
mod 'dhoppe/hosts'
mod 'puppetlabs/puppetdb'