name 'puppetlabs-passenger'
version '0.3.0'
source 'git://github.com/puppetlabs/puppetlabs-passenger.git'
author 'puppetlabs'
license 'Apache 2.0'
summary 'Puppet module for Passenger'
description 'Module for Passenger configuration'
project_page 'https://github.com/puppetlabs/puppetlabs-passenger'

dependency 'puppetlabs/apache', '>= 0.0.3'
dependency 'puppetlabs/ruby', '>= 0.0.1'
dependency 'puppetlabs/stdlib'
